import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Sharing from 'expo-sharing';
import PraxiomBackground from '../components/PraxiomBackground';
import { useAppContext } from '../AppContext';
import PraxiomAlgorithm from '../services/PraxiomAlgorithm';

const ReportScreen = ({ navigation }) => {
  const { state } = useAppContext();

  const getHealthStatus = (score) => {
    const status = PraxiomAlgorithm.getHealthStatus(score);
    return status;
  };

  const handleExportReport = async () => {
    try {
      const report = generateReportText();
      
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(report);
      } else {
        Alert.alert('Report Generated', report);
      }
    } catch (error) {
      Alert.alert('Export Error', 'Failed to export report: ' + error.message);
    }
  };

  const generateReportText = () => {
    const date = new Date().toLocaleDateString();
    
    return `
PRAXIOM HEALTH REPORT
Generated: ${date}

=== BIO-AGE SUMMARY ===
Chronological Age: ${state.chronologicalAge} years
Praxiom Bio-Age: ${state.biologicalAge.toFixed(1)} years
Deviation: ${(state.biologicalAge - state.chronologicalAge).toFixed(1)} years

=== HEALTH SCORES ===
Oral Health Score: ${state.oralHealthScore}/100
Systemic Health Score: ${state.systemicHealthScore}/100
Vitality Index: ${state.vitalityIndex}/100
Fitness Score: ${state.fitnessScore}/100

=== BIOMARKERS ===
Salivary pH: ${state.salivaryPH || 'Not measured'}
MMP-8: ${state.mmp8 || 'Not measured'} ng/mL
Flow Rate: ${state.flowRate || 'Not measured'} mL/min
hs-CRP: ${state.hsCRP || 'Not measured'} mg/L
Omega-3 Index: ${state.omega3Index || 'Not measured'}%
HbA1c: ${state.hba1c || 'Not measured'}%
GDF-15: ${state.gdf15 || 'Not measured'} pg/mL
Vitamin D: ${state.vitaminD || 'Not measured'} ng/mL

=== WEARABLE DATA ===
Heart Rate: ${state.heartRate || '--'} bpm
Daily Steps: ${state.steps || 0}
HRV: ${state.hrv || '--'}

---
Report generated by Praxiom Health
    `.trim();
  };

  const oralStatus = getHealthStatus(state.oralHealthScore);
  const systemicStatus = getHealthStatus(state.systemicHealthScore);
  const fitnessStatus = getHealthStatus(state.fitnessScore);

  return (
    <PraxiomBackground>
      <ScrollView style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity
            onPress={() => navigation.goBack()}
            style={styles.backButton}
          >
            <Ionicons name="arrow-back" size={24} color="#00d4ff" />
          </TouchableOpacity>
          <Text style={styles.title}>Health Report</Text>
          <TouchableOpacity
            onPress={handleExportReport}
            style={styles.exportButton}
          >
            <Ionicons name="share-outline" size={24} color="#00d4ff" />
          </TouchableOpacity>
        </View>

        {/* Bio-Age Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Bio-Age Summary</Text>
          <View style={styles.ageComparisonCard}>
            <View style={styles.ageColumn}>
              <Text style={styles.ageLabel}>Chronological</Text>
              <Text style={styles.ageValue}>{state.chronologicalAge}</Text>
              <Text style={styles.ageUnit}>years</Text>
            </View>
            <Ionicons name="arrow-forward" size={32} color="#00d4ff" />
            <View style={styles.ageColumn}>
              <Text style={styles.ageLabel}>Praxiom Bio-Age</Text>
              <Text style={[styles.ageValue, styles.bioAgeValue]}>
                {state.biologicalAge.toFixed(1)}
              </Text>
              <Text style={styles.ageUnit}>years</Text>
            </View>
          </View>
          
          <View style={styles.deviationCard}>
            <Text style={styles.deviationLabel}>Age Deviation:</Text>
            <Text style={[
              styles.deviationValue,
              { color: state.biologicalAge > state.chronologicalAge ? '#ef4444' : '#4ade80' }
            ]}>
              {state.biologicalAge > state.chronologicalAge ? '+' : ''}
              {(state.biologicalAge - state.chronologicalAge).toFixed(1)} years
            </Text>
          </View>
        </View>

        {/* Health Scores */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Health Scores</Text>
          
          <View style={styles.scoreCard}>
            <View style={styles.scoreHeader}>
              <Text style={styles.scoreTitle}>Oral Health</Text>
              <View style={[styles.statusBadge, { backgroundColor: oralStatus.color }]}>
                <Text style={styles.statusText}>{oralStatus.label}</Text>
              </View>
            </View>
            <Text style={[styles.scoreValue, { color: oralStatus.color }]}>
              {state.oralHealthScore}/100
            </Text>
          </View>

          <View style={styles.scoreCard}>
            <View style={styles.scoreHeader}>
              <Text style={styles.scoreTitle}>Systemic Health</Text>
              <View style={[styles.statusBadge, { backgroundColor: systemicStatus.color }]}>
                <Text style={styles.statusText}>{systemicStatus.label}</Text>
              </View>
            </View>
            <Text style={[styles.scoreValue, { color: systemicStatus.color }]}>
              {state.systemicHealthScore}/100
            </Text>
          </View>

          <View style={styles.scoreCard}>
            <View style={styles.scoreHeader}>
              <Text style={styles.scoreTitle}>Fitness</Text>
              <View style={[styles.statusBadge, { backgroundColor: fitnessStatus.color }]}>
                <Text style={styles.statusText}>{fitnessStatus.label}</Text>
              </View>
            </View>
            <Text style={[styles.scoreValue, { color: fitnessStatus.color }]}>
              {state.fitnessScore}/100
            </Text>
          </View>
        </View>

        {/* Biomarkers */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Biomarkers</Text>
          
          <View style={styles.biomarkerGroup}>
            <Text style={styles.groupTitle}>Oral Health</Text>
            <View style={styles.biomarkerRow}>
              <Text style={styles.biomarkerLabel}>Salivary pH</Text>
              <Text style={styles.biomarkerValue}>{state.salivaryPH || '--'}</Text>
            </View>
            <View style={styles.biomarkerRow}>
              <Text style={styles.biomarkerLabel}>MMP-8</Text>
              <Text style={styles.biomarkerValue}>
                {state.mmp8 ? `${state.mmp8} ng/mL` : '--'}
              </Text>
            </View>
            <View style={styles.biomarkerRow}>
              <Text style={styles.biomarkerLabel}>Flow Rate</Text>
              <Text style={styles.biomarkerValue}>
                {state.flowRate ? `${state.flowRate} mL/min` : '--'}
              </Text>
            </View>
          </View>

          <View style={styles.biomarkerGroup}>
            <Text style={styles.groupTitle}>Systemic Health</Text>
            <View style={styles.biomarkerRow}>
              <Text style={styles.biomarkerLabel}>hs-CRP</Text>
              <Text style={styles.biomarkerValue}>
                {state.hsCRP ? `${state.hsCRP} mg/L` : '--'}
              </Text>
            </View>
            <View style={styles.biomarkerRow}>
              <Text style={styles.biomarkerLabel}>Omega-3 Index</Text>
              <Text style={styles.biomarkerValue}>
                {state.omega3Index ? `${state.omega3Index}%` : '--'}
              </Text>
            </View>
            <View style={styles.biomarkerRow}>
              <Text style={styles.biomarkerLabel}>HbA1c</Text>
              <Text style={styles.biomarkerValue}>
                {state.hba1c ? `${state.hba1c}%` : '--'}
              </Text>
            </View>
            <View style={styles.biomarkerRow}>
              <Text style={styles.biomarkerLabel}>GDF-15</Text>
              <Text style={styles.biomarkerValue}>
                {state.gdf15 ? `${state.gdf15} pg/mL` : '--'}
              </Text>
            </View>
            <View style={styles.biomarkerRow}>
              <Text style={styles.biomarkerLabel}>Vitamin D</Text>
              <Text style={styles.biomarkerValue}>
                {state.vitaminD ? `${state.vitaminD} ng/mL` : '--'}
              </Text>
            </View>
          </View>
        </View>
      </ScrollView>
    </PraxiomBackground>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
  },
  backButton: {
    padding: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  exportButton: {
    padding: 8,
  },
  section: {
    padding: 20,
    paddingTop: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#00d4ff',
    marginBottom: 15,
  },
  ageComparisonCard: {
    backgroundColor: '#1e1e2e',
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginBottom: 15,
  },
  ageColumn: {
    alignItems: 'center',
  },
  ageLabel: {
    fontSize: 12,
    color: '#8e8e93',
    marginBottom: 5,
  },
  ageValue: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  bioAgeValue: {
    color: '#00d4ff',
  },
  ageUnit: {
    fontSize: 14,
    color: '#8e8e93',
    marginTop: 5,
  },
  deviationCard: {
    backgroundColor: '#1e1e2e',
    borderRadius: 16,
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deviationLabel: {
    fontSize: 16,
    color: '#ffffff',
  },
  deviationValue: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  scoreCard: {
    backgroundColor: '#1e1e2e',
    borderRadius: 16,
    padding: 20,
    marginBottom: 15,
  },
  scoreHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  scoreTitle: {
    fontSize: 16,
    color: '#ffffff',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  scoreValue: {
    fontSize: 32,
    fontWeight: 'bold',
    marginTop: 5,
  },
  biomarkerGroup: {
    backgroundColor: '#1e1e2e',
    borderRadius: 16,
    padding: 20,
    marginBottom: 15,
  },
  groupTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#00d4ff',
    marginBottom: 15,
  },
  biomarkerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2a3e',
  },
  biomarkerLabel: {
    fontSize: 14,
    color: '#8e8e93',
  },
  biomarkerValue: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '600',
  },
});

export default ReportScreen;
